#!/bin/bash

# Quick Start Guide for WordPress Automation

echo "=========================================="
echo "WordPress Automation - Quick Start"
echo "=========================================="
echo ""
echo "This system provides:"
echo "  ✓ AI-powered article generation with ChatGPT"
echo "  ✓ Automatic WordPress publishing"
echo "  ✓ Password-protected interface"
echo "  ✓ SSL/HTTPS encryption"
echo "  ✓ Docker-based deployment"
echo ""
echo "=========================================="
echo "Installation Steps"
echo "=========================================="
echo ""
echo "1. Ensure Docker is installed and running"
echo "   Check: docker --version"
echo ""
echo "2. Run the setup script:"
echo "   ./setup.sh"
echo ""
echo "3. Follow the prompts to configure:"
echo "   - HTTP Basic Auth credentials"
echo "   - Application admin credentials"
echo "   - SSL certificate (Let's Encrypt or self-signed)"
echo ""
echo "4. Access your site at: https://wp.vjgp.online"
echo ""
echo "=========================================="
echo "Configuration Required"
echo "=========================================="
echo ""
echo "After installation, configure in Settings:"
echo ""
echo "1. WordPress Configuration:"
echo "   - Site URL: https://yourblog.com"
echo "   - Username: your-wp-username"
echo "   - App Password: Generate in WordPress"
echo "     (Users → Profile → Application Passwords)"
echo ""
echo "2. OpenAI Configuration:"
echo "   - API Key: Get from https://platform.openai.com"
echo ""
echo "3. Test connections before publishing"
echo ""
echo "=========================================="
echo "Usage"
echo "=========================================="
echo ""
echo "Generate & Publish Articles:"
echo "1. Click 'Generate Article' button"
echo "2. Enter topic, keywords, tone, length"
echo "3. Review AI-generated content"
echo "4. Click 'Publish to WordPress'"
echo ""
echo "=========================================="
echo "Important Notes"
echo "=========================================="
echo ""
echo "⚠️  Security:"
echo "   - Change default passwords immediately"
echo "   - Keep credentials secure"
echo "   - Use strong passwords"
echo ""
echo "⚠️  Domain Setup:"
echo "   - Ensure wp.vjgp.online points to this server"
echo "   - Open ports 80 and 443 in firewall"
echo ""
echo "⚠️  WordPress Requirements:"
echo "   - REST API must be enabled"
echo "   - Application Passwords feature enabled"
echo "   - User must have publish_posts capability"
echo ""
echo "=========================================="
echo "Useful Commands"
echo "=========================================="
echo ""
echo "View logs:"
echo "  docker-compose logs -f"
echo ""
echo "Stop services:"
echo "  docker-compose down"
echo ""
echo "Start services:"
echo "  docker-compose up -d"
echo ""
echo "Restart services:"
echo "  docker-compose restart"
echo ""
echo "Check status:"
echo "  docker-compose ps"
echo ""
echo "=========================================="
echo ""
echo "Ready to start? Run: ./setup.sh"
echo ""
